export const AllProductStyle = {
  page: {
    backgroundColor: '#121212',
    minHeight: '100vh',
    padding: 40,
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    color: '#f0e6d2', // צבע בהיר של זהב עדין
  },
  title: {
    textAlign: 'center',
    fontSize: '2.5rem',
    fontWeight: '700',
    color: '#d4af37', // זהב קלאסי
    marginBottom: 40,
  },
  productsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)', // בדיוק 4 מוצרים בשורה
    gap: 30,
    width: '100%',
    margin: '0 auto',
    boxSizing: 'border-box',
  },
  card: {
    backgroundColor: '#1c1c1c',
    borderRadius: 12,
    padding: 20,
    boxShadow: '0 0 15px #d4af37aa',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    transition: 'transform 0.2s ease, box-shadow 0.3s ease',
    cursor: 'pointer',
    border: '2px solid transparent',
  },
  imageRow: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    marginBottom: 15,
  },
  productImage: {
    width: 140,
    height: 140,
    objectFit: 'cover',
    borderRadius: 15,
    border: '3px solid #d4af37',
  },
  infoColumn: {
    textAlign: 'center',
    marginBottom: 20,
    flexGrow: 1,
  },
  productName: {
    fontSize: '1.5rem',
    fontWeight: '700',
    marginBottom: 10,
    color: '#f1c40f',
  },
  productDesc: {
    fontSize: '1rem',
    color: '#ddd',
    marginBottom: 8,
  },
  productPrice: {
    fontSize: '1.3rem',
    fontWeight: '700',
    color: '#d4af37',
  },
  qtyLabel: {
    marginTop: 10,
    fontWeight: '600',
  },
  qtyInput: {
    width: 60,
    padding: 6,
    marginLeft: 8,
    borderRadius: 6,
    border: '1.5px solid #d4af37',
    backgroundColor: '#121212',
    color: '#f0e6d2',
    fontWeight: '600',
    textAlign: 'center',
  },
  outOfStock: {
    marginTop: 15,
    color: '#e74c3c',
    fontWeight: '700',
  },
  cartButton: {
    backgroundColor: '#d4af37',
    color: '#121212',
    border: 'none',
    borderRadius: 10,
    padding: '12px 25px',
    fontWeight: '700',
    fontSize: '1rem',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    boxShadow: '0 4px 15px #d4af37bb',
    userSelect: 'none',
    transition: 'background-color 0.3s ease',
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10000,
  },
  modalContent: {
    backgroundColor: '#222',
    padding: 30,
    borderRadius: 15,
    maxWidth: 500,
    width: '90%',
    boxShadow: '0 0 25px #d4af37cc',
  },
  filtersRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 30,
    gap: 20,
    flexWrap: 'wrap',
  },
  searchInput: {
    flex: 1,
    minWidth: 250,
    padding: '10px 15px',
    borderRadius: 8,
    border: '1.5px solid #d4af37',
    backgroundColor: '#121212',
    color: '#f0e6d2',
    fontSize: '1rem',
    fontWeight: '500',
  },
  sortSelect: {
    padding: '10px 15px',
    borderRadius: 8,
    border: '1.5px solid #d4af37',
    backgroundColor: '#121212',
    color: '#f0e6d2',
    fontSize: '1rem',
    fontWeight: '500',
  },
  logoContainer: {
    display: 'flex',
    justifyContent: 'center',
    marginBottom: 40,
    cursor: 'default',
    userSelect: 'none',
  },
  
  logoText: {
    color: '#d4af37',
    fontSize: '3rem',
    fontWeight: '600',
    fontFamily: "'Brush Script MT', cursive, 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    letterSpacing: 1,
    userSelect: 'none',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 999,
  },
  modalContent: {
    backgroundColor: '#1e1e1e',
    borderRadius: 12,
    padding: 20,
    position: 'relative',
    color: '#fff',
    boxShadow: '0 0 20px rgba(212, 175, 55, 0.4)',
  },
  
  
  

};
